# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1caaa0d7f37ef6640c5608af3e3d7b115b37ae64eca24c17b04416b8f87405664ac792e3ce68e1f3445b5ef22d4c9d81f031c4e191292448153266b427824f91

test:
  secret_key_base: 04d253217bc8eda85d902b6ffef9d466f2bd8b6b5cee5ed2f4d7162798a189d97a39c61bfca5b57c8aa46687a6c71af0a48e944ee5d565e1153a5c2608b938f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
